### PR TITLE
Add \pagebreak[1] before where... in case a column or page needs ...

### PR DESCRIPTION
**Pull request by jamesray1**
... to break or to prevent extra white lines from appearing, as happened with #509.

### CODE REVIEW

**Comment by jamesray1** [comment]
@pirapira, I must remember to leave a comment pinging you; I thought you'd be notified for this since it's in your repo.

**Comment by pirapira** [comment]
@jamesray1 ping me only on PRs of priority, which should be merged earlier.

It's my daily routine to go through YP pull-requests anyway.

**Review by pirapira — APPROVED** [review]
Looks good to me.

**Comment by jamesray1** [comment]
Well the PR was opened 11 days ago, and I wanted to make sure that this was merged to your PR before your PR was merged.

**Pull request merged**
